//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieMvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("movieMvc.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add My Favorite List.
        /// </summary>
        public static string AddMyFavoriteList {
            get {
                return ResourceManager.GetString("AddMyFavoriteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Biography.
        /// </summary>
        public static string ArtistBiography {
            get {
                return ResourceManager.GetString("ArtistBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string ArtistBirth {
            get {
                return ResourceManager.GetString("ArtistBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist General Score.
        /// </summary>
        public static string ArtistGeneralScore {
            get {
                return ResourceManager.GetString("ArtistGeneralScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Name.
        /// </summary>
        public static string ArtistName {
            get {
                return ResourceManager.GetString("ArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Photos.
        /// </summary>
        public static string ArtistPhotos {
            get {
                return ResourceManager.GetString("ArtistPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string ArtistPlaceOfBirth {
            get {
                return ResourceManager.GetString("ArtistPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Z List.
        /// </summary>
        public static string aZList {
            get {
                return ResourceManager.GetString("aZList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Movies.
        /// </summary>
        public static string FeaturedMovies {
            get {
                return ResourceManager.GetString("FeaturedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string followUs {
            get {
                return ResourceManager.GetString("followUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Horror {
            get {
                return ResourceManager.GetString("Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Artists.
        /// </summary>
        public static string MovieArtists {
            get {
                return ResourceManager.GetString("MovieArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Director.
        /// </summary>
        public static string MovieDirector {
            get {
                return ResourceManager.GetString("MovieDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Duration.
        /// </summary>
        public static string MovieDuration {
            get {
                return ResourceManager.GetString("MovieDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie General Score.
        /// </summary>
        public static string MovieGeneralScore {
            get {
                return ResourceManager.GetString("MovieGeneralScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Genre.
        /// </summary>
        public static string MovieGenre {
            get {
                return ResourceManager.GetString("MovieGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Information.
        /// </summary>
        public static string MovieInformation {
            get {
                return ResourceManager.GetString("MovieInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name.
        /// </summary>
        public static string MovieName {
            get {
                return ResourceManager.GetString("MovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Photos.
        /// </summary>
        public static string MoviePhotos {
            get {
                return ResourceManager.GetString("MoviePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Release Date.
        /// </summary>
        public static string MovieReleaseDate {
            get {
                return ResourceManager.GetString("MovieReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Trailer.
        /// </summary>
        public static string MovieTrailer {
            get {
                return ResourceManager.GetString("MovieTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Codes.
        /// </summary>
        public static string ShortCodes {
            get {
                return ResourceManager.GetString("ShortCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mail Address.
        /// </summary>
        public static string YourMailAddress {
            get {
                return ResourceManager.GetString("YourMailAddress", resourceCulture);
            }
        }
    }
}
